### ISSUE TITLE
TIME, TIMESTAMP semantics roadmap

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#10326]
( This is a roadmap (epic) issue for the problem described in https://github.com/prestodb/presto/issues/7122. I post it separately, so that the roadmap items don't get buried among other comments )

- [x] use reasonable temporal representation in tests (testability)
- [x] feature config and session toggles
- [x] use non-UTC zone as default in test and better default JVM zone (testability) (= https://github.com/prestodb/presto/issues/10078, more details there)
- [x] (https://github.com/prestodb/presto/pull/10193) engine semantics fixes 
- [ ] all casts from TIME\* to TIMESTAMP\* -- they fill date fields with `current_date`, not 1970-01-01 (see https://github.com/prestodb/presto/issues/10103#issuecomment-408256717 & following)
- [ ] Remove support for political time zones from `TIME WITH TIME ZONE` (= https://github.com/prestodb/presto/issues/10103, more details there)
- [ ] Hive changes: Hive `TIMESTAMP` should be matched to Presto `TIMESTAMP WITH TIME ZONE`
   * however https://issues.apache.org/jira/browse/HIVE-12191 & https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-TimestampstimestampTimestamps look as if Hive has changed / is going to change it's timestamp semantics, so the conversion might be hive's version dependent? References: https://issues.apache.org/jira/browse/HIVE-16614?focusedCommentId=16425288&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16425288, https://issues.apache.org/jira/browse/HIVE-12192
- [ ] Hive changes in file handlers: ORC & Parquet (especially for predicate pushdown, e.g. https://github.com/prestodb/presto/pull/10181#issuecomment-373869651), others
- [ ] Raptor changes (...?)
- [ ] JDBC connectors changes: reading (e.g. `StandardReadMappings#timestampReadMapping` assumes "old" semantics), writing and predicate pushdown
   * this may need to be split into several bullets, as databases generally vary in their support for temporal types
- [ ] other connectors ................ (to be enumerated)
- [ ] Presto JDBC changes (https://github.com/prestodb/presto/pull/9951, etc.)
- [ ] Q:  what is the complete set of implicit coercions we are going to have between TIME, TIME WITH TZ, TIMESTAMP, TIMESTAMP WITH TZ?
- [ ] Q: should `from_unixtime`, `to_unixtime` continue to work with `TIMESTAMP`?
- [ ] enable "new" correct semantics by default
- [ ] get rid of `catch Exception` for checking if input is parsable in `DateTimeUtils`

(Note: since GH doesn't send updates for edits, when adding a bullet please be sure sure to add a comment too.)

cc @martint @dain @haozhun @losipiuk

**Comment by findepi** [comment]
Added
* use non-UTC zone as default in test and better default JVM zone (testability) (= https://github.com/prestodb/presto/issues/10078, more details there)

**Comment by findepi** [comment]
added:
- all casts from TIME\* to TIMESTAMP\* -- they fill date fields with `current_date`, not 1970-01-01

**Comment by dpat** [comment]
regarding this roadmap: 

I cannot seem to determine which tasks serve to implement this functionality:
 ***Selecting values from TIMESTAMP column should return same result set no matter what is the client's session timezone*** 

is this still a goal in fixing issue #7122 ?
