### ISSUE TITLE
[Design] Connector Participating Query Optimization

### ISSUE THREAD

**Issue by highker** [prestodb/presto#13102]
# Introduction
Presto provides flexible connector interface to allow reading data from many different data source, which makes it a perfect solution to consolidate data into a big data lake. However, today the freedom we give connector is very limited and connector can only act as a data source. In many cases, the upstream system we connect to has some level of compute capacity and being able to utilize those capacity and do calculation close to data storage can help us improve the efficiency of many different connectors. Many connector such as MySQL/Cassandra/… support a subset of SQL dialect and we can execute aggregation even join in those data sources with presto receiving only partial results.

Assuming we have a connector that can read data from a fast source that supports partial computes and a slow source that only can serves as data storage. We want to rewrite the plan into a union over aggregation result of slow source and tableScan that returns intermediate results from fast data source.

# Problem of the Current Architecture
Currently, in presto, we convert AST into Plan tree after analyze step. We don’t separate LogicalPlan and ExecutionPlan so PlanNode today contains a lot of optional information we filled in for execution. As the plan converge close to physical plan, more and more information is added into PlanNode. This causes our plan to be very complex and have a lot of dependency, which contradict our principle of connector: hiding as much as implementation details of engine from connector as possible.

# Solution and New SPI Interface
Three milestones to achieve to enable connector participating query optimization:
- [x] PlanNode Expression-to-RowExpression Migration (#12546): Detach AST (`Node`) from IR (`PlanNode`). Especially, we will **replace `Expression` references in `PlanNode` with `RowExpression`**.
- [x] Introduce `ConnectorPlanOptimizer` interface for connectors to implement (#12920): A connector accepts a plan from engine, optimizes the plan, and return the plan back to engine to continue optimization. The `ConnectorPlanOptimizer` interface is shown below.
- [ ] PlanOptimizer Expression-to-RowExpression Migration (#12828): Detach AST dependency from all plan optimizers. This does not block connector participating query optimization. The ultimate goal is to remove `OriginalExpression`.

```java
 /**
 * Given a PlanNode, return a transformed PlanNode.
 * <p/>
 * The given {@param maxSubplan} is a highest PlanNode in the query plan, such that
 * (1) it is a PlanNode implementation in SPI (i.e., not an internal PlanNode), and
 * (2) all the TableScanNodes that are reachable from {@param maxSubplan} are from the current connector.
 * <p/>
 * There could be multiple PlanNodes satisfying the above conditions.
 * All of them will be processed with the given implementation of ConnectorPlanOptimizer.
 * Each optimization is processed exactly once at the end of logical planning (i.e. right before AddExchanges).
  */
@Experimental
public interface ConnectorPlanOptimizer
{
    PlanNode optimize(
            PlanNode maxSubplan,
            ConnectorSession session,
            VariableAllocator variableAllocator,
            PlanNodeIdAllocator idAllocator);
}
```

# Reference
Original connector optimizer design: #12368

**Comment by highker** [comment]
The interface will be stable after #13504 gets merged. Connector now can optimize query plans by writing its own optimizer.

**Comment by highker** [comment]
Feature will be completely available since version 0.229
