### ISSUE TITLE
Scaling The Presto Coordinator

### ISSUE THREAD

**Issue by cemcayiroglu** [prestodb/presto#13814]
### Motivation

Currently, each Presto cluster is managed by a single coordinator that becomes the bottleneck for Presto cluster to scale up. Coordinators can barely scale to around 800 to 1000 workers on a Hardware with 40 core CPU and 256GB RAM.  This creates many challenges:

- **Efficiency/Reliability:** We occasionally observe coordinator CPU utilization to be around 75%. Certain workloads can saturate the coordinator CPU and causes total failures. Any reduction in the hardware capacity makes it impossible to handle all the query scheduling on a single coordinator for our existing workloads.
- **Low Memory:** Our current batch cluster coordinators are configured to use a max heap size of 160G. This heap size limit makes it impossible to move to a low memory hardware.
- **Workload Management:** The new architecture should allow workload placement based on CPU/Memory utilization to avoid resource fragmentation and Cluster OOMs. We want to use affinity for better performance, and improve preemption for elasticity.  

We propose splitting one coordinator into multiple coordinators, and each coordinator takes a subset of the queries for a single cluster. 

### High Level Design
![queue-gw (2)](https://user-images.githubusercontent.com/16330476/70346951-51435080-1814-11ea-8eb2-8b7a6ccf505c.jpg)

Above illustrates a very high level overview of how Presto Architecture will look like. The idea is to extracting Resource Scheduling from Coordinator and just provide Resource Scheduling as a service for Presto. User will have the ability to deploy RM and a Query coordinator as a single JVM for small deployments. 

- **Query Coordinator:** Each coordinator will be responsible to execute a subset of the queries. Coordinator will receive queries from RM with their session so clients will be talking to coordinator from this moment. Coordinator will parse query, create logical plan and physical plan. Coordinator will call RM to get the list of worker nodes to execute the query. Coordinator is now responsible the create all the Remote Tasks and assigning to corresponding workers. Coordinator will return the result to the client. 
- **Queue Manager:** Queue manager will be responsible to queue queries based on the resource group configuration. It will accept queries form gateway/clients and return a session to the client. Session stays in the RM till the query gets picked up by a coordinator. Coordinators will requests queries from RM with long polling. Coordinators will be responsible for their own health so when a coordinator is under high load, it will stop/delay requesting queries from RM. RM can just the queries to coordinator in round robin. Long poll would avoid RM to know the load status of the coordinator.
- **Node Selection service:** RM is responsible to provide list of nodes to coordinators for stage executions. Selecting random Nodes, Assigning splits to Nodes for bucketed and non-bucket tables will be supported for MVP.
- **Discovery Service:** Worker nodes calls Discovery Service to register themselves to the cluster. Worker nodes will also piggyback memory status along with the heartbeats. Memory status will contain memory consumption per query.
- **OOM Killer:** OOM Killer is responsible to kill a query to take the cluster out of a deadlock. It uses the stats from worker heartbeats and determine if the cluster is OOM. It will call the corresponding Coordinator to kill the query.  
- **Gateway/Load Balancer:** Load balancer can simply does a HTTP redirect to corresponding RM based on namespace mapping. 

### Work Items 

* ### Queue Manager Split
   - [ ]  Move queue management into separate internal service.
   - [ ]  Secure submission query API to resource 
   - [ ]  Split queued and executing client API
* ### Resource Manager-only Coordinator-only server
   - [ ]  Add only start necessary services depending on server role
   - [ ]  Create a thrift service for Node Selector
   - [ ]  Integrate Discovery Service with Node Selector Service
   - [ ]  Make Coordinator call Resource manager for node selection.
   - [ ]  Make Coordinator pull queries from Queue Manager to execute.
* ### Multiple coordinators in a cluster
   - [ ]  Move LowMemoryKiller (OMM Killer) to Resource manager. 
   - [ ]  Add configuration to run shared discovery across coordinators

**Comment by BlueStalker** [comment]
hi, @cemcayiroglu do we have any updates on this? We also have some thoughts on scaling the coordinator, want to align what the community already did.

**Comment by tdcmeehan** [comment]
Superseded by #15453
