### ISSUE TITLE
[tracking] Enhancements for the UX

### ISSUE THREAD

**Issue by yhwang** [prestodb/presto#21062]
When working on the UX changes, I observed some nice-to-have enhancements to the UX. I'd like to use this issue to list and track those possible enhancements:
- [ ] In the `Split` tab of the `Query details` page, the loading and error view can be merged with the regular view by leveraging the `show/hide` CSS. This can reduce a `setTimeout` call.
- [ ] It's using bootstrap v3.3.5. It would be good to upgrade to 5.3.2 (the latest version when writing this issue) and use more components/CSS the new version provides.
- [ ] When doing the UX development, it would be good to have a lightweight webserver to serve the UX pages and proxy the APIs call to a presto coordinator. This can decouple the UX webserver from the presto server and speed up the UX dev.
- [ ] Separate some JS libraries from the generated JS pages. This can speed up the page loading time and eliminate the build warning from the webpack. 

## Expected Behavior or Use Case
It would be good to have separate PRs to address each item listed above.

## Presto Component, Service, or Connector
UX

**Comment by yhwang** [comment]
Feel free to add more items in the comments if you see fit and grab any item you'd like to work on. Let me assign this to myself and I will try to tackle them one by one.

**Comment by yhwang** [comment]
@jaystarshot good question also suggestion. Currently, session properties are not supported. This could be done in either the `SQL Client` component or `presto-js-client`. It's a good feature. Let me add it to the list.

**Comment by yhwang** [comment]
@yingsu00 I tried to run some queries to check the live plan view. I saw the` ScanFilter` like this:
<img width="210" alt="image" src="https://github.com/prestodb/presto/assets/1147320/4b2373b3-27f1-4c85-b1f2-918a263229b7">

I saw the `connectorHandle='customer.sf1.0'` and it should indicate the table. Could you elaborate more about where you want to add the table name?

**Comment by ParallaxComputers** [comment]
Hi guys, I'm working on issue number 12!

**Comment by ParallaxComputers** [comment]
Hi guys, I'm working on issue number 12!

**Comment by VidhuDashora** [comment]
Hi guys, sorry disregard the previous comment I had to remove it because it was the wrong account. Anyways, my name is Vidhu Dashora and I've started working on number 12, 

```12. The [suggestion](https://react.dev/reference/react/PureComponent#migrating-from-a-purecomponent-class-component-to-a-function) from React.js is to use function components. Refactor class components into function components.```

**Comment by tejkart** [comment]
Hi guys, my name is Tejas Karuturi and I will be working on task 13.

`13. Enforce flow checker to all UI components.`

cc: @yhwang

**Comment by yhwang** [comment]
use this to track several issues from the dependency upgrade [PR](https://github.com/prestodb/presto/pull/24167): 

- Diagram text alignment https://github.com/prestodb/presto/pull/24167#issuecomment-2636881684
- Background color in the stage diagram https://github.com/prestodb/presto/pull/24167#issuecomment-2636914304
- Inconsistent dropdown styles https://github.com/prestodb/presto/pull/24167#issuecomment-2636945982

**Comment by unidevel** [comment]
> [@unidevel](https://github.com/unidevel) can you work on the above 3?

@ethanyzhang sorry, seems I missed the notification. I will fix them this week.

**Comment by yhwang** [comment]
Actually, `query_viewer_spa.html` should not be generated when running `yarn install`. Perhaps there should be a `yarn spa` command to generate it.

**Comment by ethanyzhang** [comment]
> Actually, `query_viewer_spa.html` should not be generated when running `yarn install`. Perhaps there should be a `yarn spa` command to generate it.

@yhwang Is there any work item for this?

**Comment by yhwang** [comment]
@ethanyzhang yes, just created item 17.

**Comment by johallar** [comment]
@yhwang A couple dev life improvements/react best practices to consider that @cmatzenbach and I have discussed
* Add ESLint + prettier
* Source maps
* Split combined state objects into individual hooks eg. `const state = useState({ thing: 1 })` => `const [thing, setThing] = useState(1)
* FE router instead of separate html pages

**Comment by johallar** [comment]
Another to track is getting rid of jquery usage:
 * Element selection/modification, use react patterns (refs) to do this
 * $.ajax usage, use native fetch
 * $.extend, use native spread operator or Object.assign()

Those are the only 3 I see in use, easy to give it the axe and save us a dependency
