### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by kadaan** [prestodb/presto#2351]
### Getting Presto to build on Windows
- [ ] Support for cross platform line endings: facebook/presto#2342
- [ ] Use cross platform path separators in Takari components: jvanzyl/presto-maven-plugin#1
- [ ] Include Windows native libraries in presto-hadoop-apache2: facebook/presto-hadoop-apache2#3
- [ ] Include Windows native libraries in presto-hadoop-cdh4: facebook/presto-hadoop-cdh4#10
- [ ] Add Windows version mapping and kill.exe to testing-mysql-server: airlift/testing-mysql-server#2
- [ ] Firewall exception must be manually approved for mysqld during every build: facebook/presto#2443
- [ ] Add Windows Postgres binaries to testing-postgresql-server: airlift/testing-postgresql-server#5
- [ ] Presto-Postgresql tests fail to run: facebook/presto#2439
- [ ] Include HadoopNative components in presto-raptor so the tests run on Windows: facebook/presto#2345
- [ ] AlignedTablePrinter and VerticalRecordPrinter in Presto-Cli should support platform specific newline characters:  facebook/presto#2442

> NOTE: presto-postgresql must be disabled in the main pom.xml for Presto to build on Windows until facebook/presto#2439 is fixed.
### Running Presto on Windows
- [ ] Allow Windows OS when validating requirements in PrestoJvmRequirements: facebook/presto#2498
- [ ] Use more.com for paging in Pager class when running on Windows: facebook/presto#2521

**Comment by kadaan** [comment]
- [ ] test

**Comment by retrop** [comment]
Is there a timeline for this issue? I'd like to use Presto at my company, but Windows is a must for a certain percentage of our customers, so this issue is really holding us back.

**Comment by kadaan** [comment]
I'm very slowly working on these. All the things listed are ones I have found and fixed locally.

**Comment by kadaan** [comment]
@electrum Would you guys be able to comment on these so I can know if my suggested fixes are appropriate?

**Comment by kokosing** [comment]
@electrum Can we simply close this? I don't believe anyone will ever complete this or there is a real use case for that.

**Comment by findepi** [comment]
@kokosing i agree with you. Apparently no-one is willing to a) make it work and then b) to maintain it going forward. Closing.
